### PR TITLE
Fix linux building issues

### PR DESCRIPTION
**Pull request by lsqshr**
1. Add -lglut -lGLU to v3d_main/build.redhat to bypass the broken link to glu*
2. Use bash to call `build_plugindemo.sh` in `v3d_main/build.redhat`. It otherwise causes interpretation errors
3. In `build_plugindemo.sh`, enclose $arg with `"`, otherwise bash generates noises like `-jN operator not defined`
4. Replace `[[` with `[` since `[[` is not compatible with modern shell interpretor

After the changes, v3d compiles on my newly installed Ubuntu flawlessly.

### CODE REVIEW

**Comment by hanchuan** [comment]
building fail on Mac, many missing files!

WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/iomanager.config.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/plugins/exampleplugin2D/exampleplugin2D.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/plugins/tiff2D/tiff2D.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/plugins/tiff3D/tiff3D.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/BDVVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/HDF5Mngr.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/imBlock.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/IM_config.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/RawFmtMngr.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/RawVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/SimpleVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/SimpleVolumeRaw.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/Stack.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/StackRaw.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/StackedVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/Tiff3DMngr.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/TiledMCVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/TiledVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/TimeSeries.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/VirtualFmtMngr.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/VirtualVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/UnstitchedVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/Displacement.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/DisplacementMIPNCC.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/MergeTiles.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/PDAlgo.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/PDAlgoMIPNCC.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/StackRestorer.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/StackStitcher.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/TPAlgo.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/TPAlgoMST.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/resumer.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/utils/volumeconverter/VolumeConverter.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmBlock.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmBlockVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmStack.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmStackedVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmVirtualStack.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmVirtualVolume.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/volumemanager.config.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/crossmips/compute_funcs.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/crossmips/libcrossmips.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/tinyxml/tinystr.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/tinyxml/tinyxmlparser.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/tinyxml/tinyxmlerror.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/tinyxml/tinyxml.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/common/config.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/common/ProgressBar.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/common/QProgressSender.cpp
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/iomanager.config.h
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/ioplugins.h
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/IOPluginAPI.h
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/plugins/exampleplugin2D/exampleplugin2D.h
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/plugins/tiff2D/tiff2D.h
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/plugins/tiff3D/tiff3D.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/BDVVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/HDF5Mngr.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/imBlock.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/dirent_win.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/IM_config.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/RawFmtMngr.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/RawVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/SimpleVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/SimpleVolumeRaw.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/Stack.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/StackRaw.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/StackedVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/Tiff3DMngr.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/TiledMCVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/TiledVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/TimeSeries.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/VirtualFmtMngr.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/VirtualVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/imagemanager/UnstitchedVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/S_config.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/Displacement.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/DisplacementMIPNCC.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/PDAlgo.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/PDAlgoMIPNCC.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/StackRestorer.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/StackStitcher.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/TPAlgo.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/TPAlgoMST.h
WARNING: Failure to find: ../terafly/src/terarepo/src/stitcher/resumer.h
WARNING: Failure to find: ../terafly/src/terarepo/src/utils/volumeconverter/S_config.h
WARNING: Failure to find: ../terafly/src/terarepo/src/utils/volumeconverter/VolumeConverter.h
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmBlock.h
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmBlockVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmStack.h
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmStackedVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmVirtualStack.h
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/vmVirtualVolume.h
WARNING: Failure to find: ../terafly/src/terarepo/src/volumemanager/volumemanager.config.h
WARNING: Failure to find: ../terafly/src/terarepo/src/crossmips/my_defs.h
WARNING: Failure to find: ../terafly/src/terarepo/src/crossmips/CrossMIPs.h
WARNING: Failure to find: ../terafly/src/terarepo/src/crossmips/compute_funcs.h
WARNING: Failure to find: ../terafly/src/terarepo/src/tinyxml/tinyxml.h
WARNING: Failure to find: ../terafly/src/terarepo/src/tinyxml/tinystr.h
WARNING: Failure to find: ../terafly/src/terarepo/src/common/config.h
WARNING: Failure to find: ../terafly/src/terarepo/src/common/ProgressBar.h
WARNING: Failure to find: ../terafly/src/terarepo/src/common/QProgressSender.h
Makefile:1995: warning: overriding commands for target `moc_V3Dsubclasses.cpp'
Makefile:1789: warning: ignoring old commands for target `moc_V3Dsubclasses.cpp'
g++ -c -pipe -O3 -DTEEM_STATIC -DWITH_NONAMESPACES -DWITH_PURE_VIRTUAL -g -gdwarf-2 -w -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -D__MAC_x86_64__ -DTEEM_STATIC -D_VAA3D_TERAFLY_PLUGIN_MODE -DUSE_EXPERIMENTAL_FEATURES -DWITH_QT -DENABLE_BDV_HDF5 -D__NAWEBSERVICE__ -D_ALLOW_WORKMODE_MENU_ -DQT_SVG_LIB -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.7.1/mkspecs/macx-g++ -I. -I/usr/local/Trolltech/Qt-4.7.1/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.1/include/QtCore -I/usr/local/Trolltech/Qt-4.7.1/lib/QtNetwork.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.1/include/QtNetwork -I/usr/local/Trolltech/Qt-4.7.1/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.1/include/QtGui -I/usr/local/Trolltech/Qt-4.7.1/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.1/include/QtOpenGL -I/usr/local/Trolltech/Qt-4.7.1/lib/QtXml.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.1/include/QtXml -I/usr/local/Trolltech/Qt-4.7.1/lib/QtSvg.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.1/include/QtSvg -I/usr/local/Trolltech/Qt-4.7.1/include -I. -I../common_lib/include -I/usr/local/Trolltech/Qt-4.7.1/demos/shared -I/Developer/Examples/Qt/Demos/shared -I../common_lib/include -I../common_lib/include/hdf5 -I/usr/local/Trolltech/Qt-4.7.1/demos/shared -I../basic_c_fun -I../3drenderer -I../basic_c_fun/customary_structs -I.. -I../v3d -I../terafly/src/terarepo/src/iomanager -I../terafly/src/terarepo/src/imagemanager -I../terafly/src/terarepo/src/stitcher -I../terafly/src/terarepo/src/utils/volumeconverter -I../terafly/src/terarepo/src/volumemanager -I../terafly/src/terarepo/src/crossmips -I../terafly/src/terarepo/src/tinyxml -I../terafly/src/terarepo/src/common -I../terafly/src/control -I../terafly/src/presentation -I/System/Library/Frameworks/OpenGL.framework/Headers -I/System/Library/Frameworks/AGL.framework/Headers/ -I. -I. -F/usr/local/Trolltech/Qt-4.7.1/lib -o v3d_version_info.o v3d_version_info.cpp
make: *** No rule to make target `../terafly/src/terarepo/src/iomanager/iomanager.config.cpp', needed by `iomanager.config.o'.  Stop.

**Comment by abria** [comment]
I don't understand, the missing files are part of the terarepo submodule, which I have successfully installed in the github repo with git add submodule.

Xiaoxiao, any suggestions? Mean while I will have a look, after dinner.

Alessandro

**Comment by hanchuan** [comment]
I double checked it seems I do not have these files...

I was just running build.macx -m -j4 -noplugins

**Comment by berl** [comment]
Hanchuan, the submodule needs to be initiated and updated on your local machine:

git submodule init
git submodule update

will put all the terafly code in place

**Comment by hanchuan** [comment]
still failed after these 2

**Comment by XiaoxiaoLiu** [comment]
what is the error msg? have you successfully pulled the submodule code?

**Comment by hanchuan** [comment]
WARNING: Failure to find: ../terafly/src/terarepo/src/iomanager/ioplugins.h

**Comment by abria** [comment]
Hanchuan, please try again after updating the code.

**Comment by XiaoxiaoLiu** [comment]
It's working now. Thanks alessandro!
I have added the "--recursive" option in the wiki  build instructions.

We should add "git submodule update" in all build scripts?

**Comment by abria** [comment]
Well, I guess yes. The submodule I have just added contains the I/O core functions of TeraFly and of TeraStitcher (which indeed is the GitHub repo I have added with `git add submodule`). It is likely that there will be bug fixes. So if we want them to be automatically included in the Vaa3D repo, `git submodule update --init --recursive` should be added in the scripts.

Honestly I thought this process would have been much smoother. Sorry guys!

**Comment by hanchuan** [comment]
you want me to clone again instead of update?

"git submodule update" seems doing nothing...

**Comment by XiaoxiaoLiu** [comment]
I have added  "git submodule update --init --recursive" in the build scripts.
You can give it a try. It's working for me.

**Comment by abria** [comment]
Xiao Xiao,

I didn't have the same issue on my Linux, anyway I think I fixed the ambiguous uint8 and uint32. Please could you check?

Thanks

**Comment by XiaoxiaoLiu** [comment]
hmm, that fixed it fore me.
New linking error though:

v3dr_glwidget.o: In function `V3dR_GLWidget::lookAlong(float, float,
float)':
v3dr_glwidget.cpp:(.text+0x55e6): undefined reference to `gluLookAt'
renderer.o: In function `Renderer::paint()':
renderer.cpp:(.text+0x4a7d): undefined reference to `gluNewQuadric'

**Comment by berl** [comment]
I think updating the submodule in the build scripts may not be a good idea. The user won’t have any control over the local submodule code because it will be updated during the build.

@xiaoxiao instead can you just check to make sure the terafly src directory exists before running git submodule update ?

The automatic pull of the submodule makes sense for a release branch of the project, e.g. vaa3d 3.2 build scripts would go get a set version of terafly before building, but for the current master branch (which is both dev and release) I suggest that we need to let the developers have the flexibility to work on their own machine and still use the build scripts as-is.

-Brian

**Comment by XiaoxiaoLiu** [comment]
Makes sense!
Sounds like we need to start to have a "release" branch :)
and call our current  master "dev".

**Comment by hanchuan** [comment]
where this submodule issue came from? I thought we had only one trunk...

**Comment by hanchuan** [comment]
...and I have to say, I really dislike merging of code unless it is
absolutely unavoidable. Merging several branches is a very painful process
and very distracting, always introducing a lot of more bugs than originally
splitting into various branches. If there is a need to separate a module, I
will encourage using a clearly defined interface to develop a separate,
modulized, body of code (e.g. a plugin).

**Comment by berl** [comment]
That's a valid point Hanchuan-  it places an obligation on developers to do testing on the full package, not just submodules.

Just a note:
The need for a  dev and release branch is separate from this issue because the release branches will basically be dead-ends and never merged with anything.

Sent from my iPhone

On Mar 11, 2016, at 10:11 AM, Hanchuan Peng <notifications@github.com<mailto:notifications@github.com>> wrote:

...and I have to say, I really dislike merging of code unless it is
absolutely unavoidable. Merging several branches is a very painful process
and very distracting, always introducing a lot of more bugs than originally
splitting into various branches. If there is a need to separate a module, I
will encourage using a clearly defined interface to develop a separate,
modulized, body of code (e.g. a plugin).

On Fri, Mar 11, 2016 at 10:06 AM, Hanchuan Peng <hanchuan.peng@gmail.com<mailto:hanchuan.peng@gmail.com>>
wrote:

> where this submodule issue came from? I thought we had only one trunk...
>
> On Fri, Mar 11, 2016 at 9:53 AM, Xiaoxiao Liu <notifications@github.com<mailto:notifications@github.com>>
> wrote:
>
>> Makes sense!
>> Sounds like we need to start to have a "release" branch :)
>> and call our current master "dev".
>>
>> On Fri, Mar 11, 2016 at 9:41 AM, berl <notifications@github.com<mailto:notifications@github.com>> wrote:
>>
>> > I think updating the submodule in the build scripts may not be a good
>> > idea. The user won't have any control over the local submodule code
>> because
>> > it will be updated during the build.
>> >
>> > @xiaoxiao instead can you just check to make sure the terafly src
>> > directory exists before running git submodule update ?
>> >
>> > The automatic pull of the submodule makes sense for a release branch of
>> > the project, e.g. vaa3d 3.2 build scripts would go get a set version of
>> > terafly before building, but for the current master branch (which is
>> both
>> > dev and release) I suggest that we need to let the developers have the
>> > flexibility to work on their own machine and still use the build scripts
>> > as-is.
>> >
>> > -Brian
>> >
>> > From: Xiaoxiao Liu [mailto:notifications@github.com]
>> > Sent: Thursday, March 10, 2016 12:13 PM
>> > To: Vaa3D/v3d_external <v3d_external@noreply.github.com<mailto:v3d_external@noreply.github.com>>
>> > Cc: Brian Long <brianl@alleninstitute.org<mailto:brianl@alleninstitute.org>>
>> > Subject: Re: [v3d_external] Fix linux building issues (#2)
>> >
>> >
>> > I have added "git submodule update --init --recursive" in the build
>> > scripts.
>> > You can give it a try. It's working for me.
>> >
>> > -
>> > Reply to this email directly or view it on GitHub<
>> > https://github.com/Vaa3D/v3d_external/pull/2#issuecomment-195027655>.
>> >
>> > -
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/Vaa3D/v3d_external/pull/2#issuecomment-195473644>.
>>
>> >
>>
>> -
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Vaa3D/v3d_external/pull/2#issuecomment-195477742>.
>>
>
>

-

**Comment by hanchuan** [comment]
Agree! I was talking about the dev branch, apparently. I would avoid trying
to maintain multiple dev branches and merge them from time to time. It's
simply too complicated to me , :-).
